### ISSUE TITLE
module003 Classses properties

### ISSUE THREAD

**Issue by Aloren** [pyadmitrij/GoJavaOnline#3]
Properties of classes should not be hardcoded inside classes.

Hiding fields is very bad practice -- don't do this (Class File has field name and class Audio has field name). Instead class File should define constructor with 2 args (String name, int size). Then class Audio will have the following constructor:
public Audio(String name, int size) {
super(name, size);
}

The same relates to all classes in music, flower and file packages.

**Comment by pyadmitrij** [comment]
ok
